### PR TITLE
Allow puppet/systemd 7.x

### PR DESCRIPTION
**Pull request by dploeger**
#### Pull Request (PR) description
This updates the systemd dependency

### CODE REVIEW

**Comment by TheMeier** [comment]
why not < 8 for puppet-systemd?

**Comment by dploeger** [comment]
@TheMeier makes sense now as well. The branch is a bit old.

**Comment by dploeger** [comment]
Oh. I see now, that the rest was already updated. 😆

**Comment by TheMeier** [comment]
same as https://github.com/voxpupuli/puppet-jira/pull/423

**Pull request closed without merging**
