### PR TITLE
Issue #135 Fix

### PR DESCRIPTION
**Pull request by AlexanderNZ**
I removed the conditional statement relating to JasperListener to fix Issue #135 

Hope that helps :)

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @AlexanderNZ, thanks for the contribution. Could you please take a look at the travis issues?

**Comment by AlexanderNZ** [comment]
Have fixed the issues that broke the build :) 
There was a line in `spec/classes/jira_config_spec.rb` that ensured that JasperListener was present. I didn't realise that was there so just a case of removing that line. 

Ive just removed that line, and not the surrounding i`t {}` statement since I wasn't super sure if it was still needed. If you want me to remove that as well then let me know!

**Comment by bastelfreak** [comment]
Hi,

thanks for the fix \o/
could you please adjust the last commit title? Just rename the title to something like "remove spec test for removed code" and keep the commit message.

**Comment by AlexanderNZ** [comment]
That is done, sorry for the dirty merge.

**Comment by bastelfreak** [comment]
I'm not sure, but I think you messed up the git history. You can fix that by rebasing and squashing. If you need help for that you can join our #voxpupuli channel on freenode.

**Comment by AlexanderNZ** [comment]
I've fixed those commits up, and rewritten a better message.

**Comment by bastelfreak** [comment]
@AlexanderNZ thank you so much!

**Pull request merged**
