### PR TITLE
Issue #215 - Disable user, need to update spec tests

### PR DESCRIPTION
**Pull request by cyberious**

### CODE REVIEW

**Comment by bastelfreak** [comment]
Thanks for this PR @cyberious!

**Comment by bastelfreak** [comment]
@cyberious is this still WIP?

**Comment by cyberious** [comment]
Yes will be pushing changes tomorrow.

**Comment by cyberious** [comment]
Updated, was waiting to get back to writing the spec tests around it.

**Comment by bastelfreak** [comment]
Hi @cyberious, can you take a look at the failing spec tests?

**Comment by eriksalinenike** [comment]
Is there an ETA when this will be release to Puppet Forge?

**Comment by dhollinger** [comment]
@cyberious is there any work left on this PR?

**Comment by cyberious** [comment]
Nope should be gtg

**Pull request merged**
