### PR TITLE
Add Puppet 8 support

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by danifr** [comment]
Hi @bastelfreak, since I am preparing the 5.2.0 release, does it make sense to merge some of the opened PR?
We have some that are quite safe to merge

**Comment by danifr** [comment]
- https://github.com/voxpupuli/puppet-jira/pull/407
- https://github.com/voxpupuli/puppet-jira/pull/403
- https://github.com/voxpupuli/puppet-jira/pull/401
- https://github.com/voxpupuli/puppet-jira/pull/398
- https://github.com/voxpupuli/puppet-jira/pull/397
- And of course this one (or a newer version of it) https://github.com/voxpupuli/puppet-jira/pull/394

**Comment by bastelfreak** [comment]
None of the linked PRs have passing CI. This needs to be fixed before we continue. I currently don't have tue capacity to work on them. If you want, you can. pick those up, fix CI and resubmit them as new PRs.

**Comment by danifr** [comment]
I see. I don't mind doing the work, but my knowledge about this is close to zero (and most of the CI logs have expired and are no longer available.)

If there is something easy I can start with please let me know.

About modulesync, actually for release I am preparing I rebased from your https://github.com/voxpupuli/puppet-jira/pull/394 because I couldn't wrap my head around the instructions in https://voxpupuli.org/docs/releasing_version/

The docs say "Run modulesync to ensure the dotfiles are up-to-date." but it does not explain how.

Thanks

**Review by SimonHoenscheid — APPROVED** [review]
Technically LGTM, lets get this pipeline green

**Comment by h-haaks** [comment]
@bastelfreak with #414 this i obsolete. Is it ok to just close and delete the branch?

**Comment by bastelfreak** [comment]
This isn't obsolete. The metadata.json currently doesn't list Puppet 8.

**Review by h-haaks — APPROVED** [review]

**Pull request merged**
