### PR TITLE
Modified use of staging::extract to work around missing strip support…

### PR DESCRIPTION
**Pull request by LTangaF**
… of unzip

This addresses https://github.com/puppet-community/puppet-jira/issues/103

### CODE REVIEW

**Comment by jyaworski** [comment]
Hello:

What's the status of this PR? Can it be rebased?

**Comment by LTangaF** [comment]
I can rebase this if someone is ready to merge it. I'd just like to avoid doing that multiple times.

**Comment by bastelfreak** [comment]
Please do the rebase. We should be able to merge it a few hours after your update. Otherwise please ping in #voxpupuli on freenode IRC.

**Comment by LTangaF** [comment]
Tested this locally with our company's test harness, which is unfortunately quite divergent from this module's.  Pushed update.

**Comment by LTangaF** [comment]
Looks like lint is unhappy. I'll fix that and re-push.

**Comment by LTangaF** [comment]
I'll have to reproduce the rspec test that is failing here and see if I can duplicate it and fix it.

**Comment by LTangaF** [comment]
Alright. Found the issue with my code.  Didn't pick up the recent change to use $product_name in setting up the install directories.  Pushed up fix and it looks like the travis tests passed.

**Pull request merged**
