### PR TITLE
modulesync 4.0.0

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 4.0.0

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
EL6 failed:
```
       	**********     Wrong JVM version! You are running with java version "1.7.0_261" but JIRA requires at least 1.8 to run.      **********
```

Previously it didn't run and I'm not sure if Java 8 is available on EL6. Since it's going EOL I'm recommending to drop EL6.

**Review by ekohl — CHANGES_REQUESTED** [review]
It should also drop `.sync.yml` which is now redundant.

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Not sure why PostgreSQL doesn't start on Ubuntu 16.04. It may be due to PIDFIle. https://github.com/voxpupuli/puppet-jira/pull/326 also broke Ubuntu due to bashisms. The next failure on Ubuntu 18.04 is that it doesn't recognize openjdk 11. Looks like the default version doesn't support that but recent ones do.

For now I'm giving up on this and someone who actually uses the module needs to step in.

**Comment by kenyon** [comment]
> Not sure why PostgreSQL doesn't start on Ubuntu 16.04. It may be due to PIDFIle. #326 also broke Ubuntu due to bashisms. The next failure on Ubuntu 18.04 is that it doesn't recognize openjdk 11. Looks like the default version doesn't support that but recent ones do.
> 
> For now I'm giving up on this and someone who actually uses the module needs to step in.

This is the only remaining issue preventing the tests from passing. PostgreSQL on Ubuntu 16.04 starts but systemd hangs at "activating":

```console
root@ubuntu1604-64-1:~# systemctl status postgresql@9.5-main
● postgresql@9.5-main.service - PostgreSQL Cluster 9.5-main
   Loaded: loaded (/lib/systemd/system/postgresql@.service; disabled; vendor preset: enabled)
   Active: activating (start) since Sun 2021-02-14 07:56:53 UTC; 37s ago
  Process: 6281 ExecStart=/usr/bin/pg_ctlcluster --skip-systemctl-redirect %i start (code=exited, status=0/SUCCESS)
   CGroup: /docker/378b796a749da8c903ba5f6f2da85ecf2ebd218038129f71e9f39a1c084d1d9a/system.slice/system-postgresql.slice/postgresql@9.5-main.service
           ├─6286 /usr/lib/postgresql/9.5/bin/postgres -D /var/lib/postgresql/9.5/main -c config_file=/etc/postgresql/9.5/main/postgresql.conf
           ├─6288 postgres: 9.5/main: checkpointer process
           ├─6289 postgres: 9.5/main: writer process
           ├─6290 postgres: 9.5/main: wal writer process
           ├─6291 postgres: 9.5/main: autovacuum launcher process
           └─6292 postgres: 9.5/main: stats collector process

Feb 14 07:56:53 ubuntu1604-64-1 systemd[1]: Starting PostgreSQL Cluster 9.5-main...
Feb 14 07:56:55 ubuntu1604-64-1 systemd[1]: postgresql@9.5-main.service: New main PID 6286 does not belong to service, and PID file is not owned by root. Refusing.
Feb 14 07:56:55 ubuntu1604-64-1 systemd[1]: postgresql@9.5-main.service: New main PID 6286 does not belong to service, and PID file is not owned by root. Refusing.

root@ubuntu1604-64-1:~# ll /run/postgresql/9.5-main.pid
-rw-r--r-- 1 postgres postgres 5 Feb 14 07:56 /run/postgresql/9.5-main.pid

root@ubuntu1604-64-1:~# cat /run/postgresql/9.5-main.pid
6286
```

:shrug:

**Comment by ekohl** [comment]
We have a pidfile workaround in our templates which uses an older version of Ubuntu 16.04 but I'd prefer to drop Ubuntu 16.04. It's going EOL soon anyway.

**Comment by ekohl** [comment]
This is green, but care should be taken. https://github.com/voxpupuli/puppet-jira/pull/345 is included and I've included an alternative to https://github.com/voxpupuli/puppet-jira/pull/341 as well.

**Review by bastelfreak — COMMENTED** [review]
I can't approve it, but looks good to me.

**Comment by ekohl** [comment]
@kenyon thoughts?

**Comment by kenyon** [comment]
Looks good to me. Rebased on current master. Updated the Jira version in the alternative commit to #341.

**Review by ekohl — APPROVED** [review]
Let's get this in. I opened https://github.com/voxpupuli/puppet-jira/issues/346 for the Ubuntu 16.04 -> 18.04 change for the changelog.

**Pull request merged**
