### PR TITLE
fixes issue #162 - add pool_test_on_borrow to dbconfig.mysql.xml.erb

### PR DESCRIPTION
**Pull request by ryandb**

### CODE REVIEW

**Comment by sacres** [comment]
Since we actually want this always set to 'false', should we not just set it on the dbconfig rather than create a lookup?

**Comment by ffrank** [comment]
According to the `README`, the `pool_test_on_borrow` value defaults to `true`, though. Am I missing something?

**Comment by sacres** [comment]
There is no value set for `pool_test_on_borrow` for the mysql dbconfig.xml currently and since we always want it set to false, rather than check a variable, I thought we might just set it explicity in the dbconfig.mysql.xml.erb

**Comment by ffrank** [comment]
Sorry if I'm being dense, but I still don't see why it's important or even desirable that the `mysql dbconfig` always receives a `false` value.

It was my initial understanding that that was a bug, and that this PR is supposed to fix it, by using the appropriate parameter value rather than ignoring it. Is that wrong?

**Comment by sacres** [comment]
@ffrank No, the PR isn't _wrong_ per se. I was suggesting & asking the community and the submitter if we should just explicitly set it. 
With regard to why it should be set to false: https://confluence.atlassian.com/jirakb/health-check-database-configuration-792636748.html for example. I'm good with the PR, though think if it's a variable we (I'm game to submit another PR myself updating  `puppet-jira/examples/jira_mysql_install.pp` as well, aside from this).

**Comment by sacres** [comment]
Actually, according to: https://confluence.atlassian.com/adminjiraserver071/tuning-database-connections-802592189.html or https://confluence.atlassian.com/jira064/tuning-database-connections-720411760.html ; Atlassian recommends the setting to be 'false' though _if_ unspecified defaults to 'true'  . Perhaps a better approach would be to change the default here: https://github.com/voxpupuli/puppet-jira/blob/master/manifests/init.pp `$pool_test_on_borrow = true,` to recommended of 'false' .

**Comment by ryandb** [comment]
@sacres - agree wrt defaulting to false.  I will revise the PR.  Thanks.

**Comment by sacres** [comment]
Nice, @ryandb ! We should probably amend the `README` , https://github.com/voxpupuli/puppet-jira/blob/master/README.md#L266 to reflect that change as well though.

**Comment by ffrank** [comment]
Do keep in mind, though, that we will likely need a major release if we want to do this kind of API change.

cc @mkrakowitzer

**Comment by ryandb** [comment]
Changed readme as suggested -- thanks.

**Comment by sacres** [comment]
LGTM @ryandb . What needs to be done to promote the major release you mentioned @ffrank ?

**Comment by ffrank** [comment]
Essentially, if this gets merged to master, we just need to be careful to not create another point release that includes this.

In case there are some things still in the pipeline that also need a major release, it might make sense to hold this back until those are ready. I don't have a good overview over this module. Hope someone will speak up with some authority.

When in doubt, we can always just go ahead and make the version jump. But I'd like a review from at least one other maintainer.

**Comment by bastelfreak** [comment]
looks good to me, discussed it with @sacres on IRC.

**Pull request merged**
