### PR TITLE
Fix for jira::facts not working with All-in-One Puppet 4.x agent

### PR DESCRIPTION
**Pull request by dpisano**
This is a propose fix for issue #151. I have not been able to do any testing with other version of puppet, so I don't know if it would break anything with puppet 3.x.

### CODE REVIEW

**Comment by dpisano** [comment]
Looks like this is being covered better via pull request #115. I'm going to close this as it is a duplicate.

**Comment by alexjfisher** [comment]
@dpisano Hi!  https://github.com/voxpupuli/puppet-jira/pull/115 seems to have been closed without having been merged.  Would you be interested in reopening this PR?

**Comment by dpisano** [comment]
It looks like #158 pick up where #115 left off. If would like I would be more then happy to reopen this PR.

**Comment by dpisano** [comment]
Reopening as per @alexjfisher request.

**Comment by juniorsysadmin** [comment]
Close in favor of #158 ?

**Comment by dpisano** [comment]
#158 does look to be in better shape. I have no objections in closing this in favor of #158 if you like.

**Comment by juniorsysadmin** [comment]
Closing in favor of #158

**Pull request closed without merging**
